baseURL = "https://schleig.com/"
languageCode = "en-us"
title = "Schleig.com"
theme = "coder" # set the theme
copyright = "2018"

[blackfriday]
    hrefTargetBlank = true

[permalinks] # configure post and fixed pages permalinks
    post = "posts/:title/"
    default = ":title/"

[params] # theme parameters
    author = "Daniel Schleig" # author's name
    info = "AWS Certified, Solution Architect, IT Security Specialist" # author's job title or info
    description = "Daniel Schleig's Personal Website" # site description
    keywords = "blog,developer,personal" # site keywords
    
# Social links
# [[params.social]]
#    name = "Github"
#    weight = 1
#    url = "https://github.com/schleig/"
[[params.social]]
    name = "LinkedIn"
    weight = 1
    url = "https://www.linkedin.com/in/danielschleig/"
[[params.social]]
    name = "Email"
    weight = 2
    url = "mailto:daniel@schleig.com"
	
# Menu links
# [[menu.main]]
#    name = "Blog"
#    weight = 1
#    url = "/blog/"
[[menu.main]]
    name = "Projects"
    weight = 1
    url = "/projects/"
#[[menu.main]]
#    name = "Resume"
#    weight = 3
#    url = "https://daniel.schleig.com/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"